del /s *.tmp
del /s *.aux 
del /s *.acn
del /s *.glo
del /s *.ist
del /s *.lof
del /s *.log
del /s *.lot
del /s *.syg
del /s *.acr
del /s *.toc
del /s *.alg
del /s *.sc
del /s *.ps
del /s *.bbl
del /s *.blg
del /s *.glg
del /s *.gls
del /s *.slg
del /s *.syi
del /s *.synctex
del /s *.tdo
del /s *.aux
del /s *.tps
del /s *.nav
del /s *.out
del /s *.snm
del /s *.bib.bak
del /s *.idx
del /s *.ilg
del /s *.ind
del /s *.dvi